{% set name = "django-bootstrap4" %}
{% set version = "26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/django_bootstrap4-{{ version }}.tar.gz
  sha256: 3d277c350f77ccfd2800f1997c6e79ac05c15d614a8b114764449774a82d9307

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - django >=4.2
    - beautifulsoup4 >=4.10.0

test:
  source_files:
    - tests
    - manage.py
  imports:
    - bootstrap4
    - bootstrap4.templatetags
  commands:
    - pip check
    - python manage.py test
  requires:
    - pip
    - gdal
    - python {{ python_min }}

about:
  home: https://github.com/zostera/django-bootstrap4
  summary: Bootstrap 4 for Django
  license: BSD-3-Clause
  license_file: LICENSE
  description: Write Django as usual, and let django-bootstrap4 make template output into Bootstrap 4 code.
  doc_url: http://django-bootstrap4.readthedocs.io/
  dev_url: https://github.com/zostera/django-bootstrap4

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - maksdan
    - davner
